[package]
name = "gltfunroll"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
glam = { version = "0.30", features = ["serde"] }
gltf = "1"
idm = "0.4"
serde = { version = "1", features = ["derive"] }
